//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summary
    {
        public int Id { get; set; }
        public string IdOfAuthor { get; set; }
        public string FIO { get; set; }
        public string Info { get; set; }
        public int Experience { get; set; }
        public System.DateTime DatePublication { get; set; }
        public int Age { get; set; }
        public bool Sex { get; set; }
        public string BaseProfession { get; set; }
    }
}
